class Constants {
  // Cài đặt tên các action
  FIND_ALL_ITEM = "FIND_ALL_ITEM";
  PAGED_ITEM = "PAGED_ITEM";
  FIND_SINGLE_ITEM = "FIND_SINGLE_ITEM";
  ADD_ITEM = "ADD_ITEM";
  UPDATE_ITEM = "UPDATE_ITEM";
  REMOVE_ITEM = "REMOVE_ITEM";
  INCREASE_ITEM = "INCREASE_ITEM";
  DECREASE_ITEM = "DECREASE_ITEM";

  SHOW_ALL_ITEM = "SHOW_ALL_ITEM";
  SHOW_PAGED_ITEM = "SHOW_PAGED_ITEM";
  SHOW_SINGLE_ITEM = "SHOW_SINGLE_ITEM";
}

export default new Constants();
